# https://nixpacks.com/docs/configuration/file
# set up some variables to minimize annoyance
[variables]
  NODE_ENV = 'production' # set the node environment to production
  NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update notification is relatively useless in a production environment
  NPM_CONFIG_FUND = 'false' # the fund notification is also pretty useless in a production environment
[phases.build]
  cmds = ["echo building!", "echo $NODE_ENV", "npm run build"]